config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home' 
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :articles
  resources :users, except: [:new]
  resources :categories
 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    
    validates :title, presence: true, length: {minimum:3,maximum:10}
    validates :description, presence: true,length: {minimum:3,maximum:500}
    validates :user_id, presence: true
    
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
# category model
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 15}, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :articles, dependent: :destroy
   
    before_save {self.email = email.downcase }
    validates :username, presence: true,
              length:{minimum: 3, maximum: 15},
              uniqueness: { case_sensitive: false }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true,length:{maximum: 105},
              uniqueness: { case_sensitive: false },
              format: {with:  VALID_EMAIL_REGEX }

end

app/controllers/application_controller.rb
# Application controller
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'Please login'
      redirect_to login_url
    end
  end
end

app/controllers/articles_controller.rb
# Articles Controller
class ArticlesController < ApplicationController
  before_action :find_article, only: %i[edit update show destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, except: %i[index show new create]

  def index
    @articles = Article.order('updated_at DESC')
                       .paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def show; end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      flash[:success] = 'Article was created !'
      redirect_to article_path(@article)
    else
      flash[:danger] = 'could not create the article'
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was updated !'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Artice was successfully deleted'
    redirect_to articles_url
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids:[])
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    flash[:danger] = 'You can only modify your own articles' if
    current_user != @article.user && !current_user.admin?
  end
end

app/controllers/categories_controller.rb
# categories controller
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]
  def index
    @categories = Category.order('updated_at DESC').paginate(page: params[:page], per_page: 3)
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 1)
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category successfuly created'
      redirect_to categories_url
    else
      flash[:danger] = 'Something went wrong, please try again'
      render :new

    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = 'Category successfuly updated'
      redirect_to categories_url
    else
      flash[:danger] = 'Something went wrong, please try again'
      render :edit
    end
  end

  def destroy; end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !require_user && !current_user.admin?
      flash[:danger] = 'Only admin can perform this action'
      redirect_to categories_url
    end
  end
end

app/controllers/pages_controller.rb
# Pages controller
class PagesController < ApplicationController
  def home
    redirect_to articles_url if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
# sessions controller
class SessionsController < ApplicationController
  def new; end

  def edit; end

  def create
    # debugger
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.username}"
      redirect_to users_url
    else
      flash[:danger] = 'Check the input and try again'
      render :new
    end
  end

  def update; end

  def destroy
    session[:user_id] = nil
    flash[:danger] = 'logged out'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def index
    @users = User.paginate(page: params[:page], per_page: 3)   
  end
  def show
   
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    # @user_paginate = user.paginate(page: params[:page], per_page: 2)
  end

  def new
    @user = User.new
  end

  def edit
             
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Account created successfully!'
      redirect_to user_url(@user)
    else
      flash[:danger] = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  def update
    if  @user.update(user_params)
      flash[:success] = "Account updated successfully!"
      redirect_to root_url
      else
      flash[:danger] = "Oops, couldn't update account. Please make sure you are using a valid email and password and try again."
      render :edit
    end
  end

  def destroy
    
    @user.destroy
    flash[:danger] = 'User was successfully deleted'
    redirect_to users_path
  end
  
  private
  
  def user_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.require(:user).permit(:username, :email, :password)
  end

  def user_find
    @user = User.find(params[:id])
  end
  def require_same_user
    if @user != current_user && !current_user.admin?
      flash[:danger] = "You can only modify your own account"
      redirect_to users_url      
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 100) %>
            </div>
                <div class="article-meta-details">
                    <small>Created by: <%= link_to article.user.username, user_url(article.user_id) %>,
                    <%= time_ago_in_words(article.created_at) %> ago,
                    last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                </div>
                <% if article.categories.any? %>
                    <p>Categories <%= render article.categories %></p>
                <% end%>
                <% if logged_in? && (current_user == article.user || current_user.admin? ) %>
               <div class="article-actions">
                    <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                    <%= link_to "Delete this article", article_path(article), method: :delete,
                        data: { confirm: "Are you sure you want to delete the article?"},
                    class: "btn btn-xs btn-danger" %>
                </div>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>

<div class='row'>
    <div class='col-xs-12'>
        <%# <%= form_for(@article,:html =>{class: "form-horizontal",role:"form"}) do |f| %>
        <%= form_with model: @article, local: true, class: 'form-horizontal' do |f| %>
            <div class='form-group'>
            <div class="control-label col-sm-2">
                <%= f.label :title %> <br> 
                </div>
                <div class='col-sm-8'>
                <%= f.text_field :title, class: 'form-control', placeholder: 'Title of the article',autofocus: true %>
                </div>
            </div>

            <div class='form-group'>
                <div class="control-label col-sm-2">
                    <%= f.label :description %> <br>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
                </div>
            </div>

            <div class='form-group'>
                <div class="control-label col-sm-2">
                    <%= f.label :categories %> <br>
                </div>
                <div class="col-sm-8">
                    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                    <% end %>
                </div>
            </div>



            <div class='form-group'>
                <div class="col-sm-offset-2 col-sm-10">
                    <%=f.submit class:'btn btn-primary btn-lg'%>
                </div>
            </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
    <div>
</div>

app/views/articles/edit.html.erb
<h1 align='center'>Editing page</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<%= link_to "Create Article", new_article_url, style: 'margin: 50px'%>
<div align="center">
<%= will_paginate %>
</div>
<h5 align="center">Categories</h5>
<div align="center">
    <ul class='list-inline'>
        <% Category.all.each do |c| %>
            <li class='list-inline-item'>
            <%= link_to c.name, category_path(c), :remote => true %>    
            </li>
            <li class='list-inline-item'>
              |
            </li>
        <% end %>
    </ul>
    </div>
    <div id="filter"></div>
<%= render 'article', obj: @articles %>
<div align="center">
<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align='center'>NEW ARTICLE</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
<h6> Created by: 
<% if @article.user == current_user %>
 <%= link_to 'You', user_url(@article.user_id) %>
  <% else %>
   <%= link_to @article.user.username, user_url(@article.user_id) %>
<% end %>
<hr>
<h4 class="center description"><strong>Description:</strong></h4>
<hr>
<%= simple_format(@article.description) %>
<br>
<% if @article.categories.any? %>
    <p>Categories <%= render @article.categories %></p>
<% end%>
<div class="article-actions">
<% if logged_in? && (current_user == @article.user || current_user.admin? ) %>
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete this article", article_path(@article), method: :delete,
    data: { confirm: "Are you sure you want to delete the article?"},
    class: "btn btn-xs btn-danger" %>
<%end%>
<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
</div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to "| #{category.name} |", category_path(category) %> </span>

app/views/categories/_filter.html.erb
<h1 aign="center">
Category:<b> <%= "#{@category.name.capitalize}"%></b></h1>
<%= render 'articles/article', obj: @category_articles %>
<div class="col-xs-4 col-xs-offset-4"> 
    [ <%= link_to "View all categories", categories_url %> ]
</div>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category%>

<%= form_for(@category,:html =>{class: "form-horizontal",role:"form"}) do |f| %>
<div class='form-group'>
<div class="control-label col-sm-2">
    <%= f.label :name %> <br> 
    </div>
    <div class='col-sm-8'>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter category name',autofocus: true %>
    </div>
</div>

<div class='form-group'>
  <div class="col-sm-offset-2 col-sm-10">
   <%=f.submit class:'btn btn-primary btn-lg'%>
  </div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
  [ <%= link_to "Cancel request and return to articles listing", articles_url %> ]
</div>

app/views/categories/edit.html.erb
<h1 align = "center">edit Categories</h1>
<%= render 'form', obj: @category%>

app/views/categories/index.html.erb
<h1>Categories</h1>
<hr>
<div align="center">
<%= will_paginate @categories%>
    <% @categories.each do |c| %>        
        <div class="row">
            <div class="well col-md-4 col-md-offset-4">
                <div class="article-title">
                <%= link_to c.name, category_path(c) %>
                </div>
                <div style=" text-align:right; color: #737373" >
                    <%= pluralize(c.articles.count, 'article', 'articles') %>   
                </div>
            </div>
        </div>        
    <% end %>
    <%= will_paginate @categories%>
</div>

app/views/categories/new.html.erb
<h1 align = "center">create new Categories</h1>
<%= render 'form', obj: @category%>

app/views/categories/show.html.erb
<h1 aign="center">
Category:<b> <%= "#{@category.name.capitalize}"%></b></h1>
<% if logged_in? && current_user.admin? %>
    <%= link_to "Edit Category", edit_category_url(@category), style: 'margin: 50px'%>
<% end %>
<div align="center">
<%= will_paginate @category_articles%>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div class="col-xs-4 col-xs-offset-4"> 
    [ <%= link_to "View all categories", categories_url %> ]
</div>
<div align="center">
<%= will_paginate @category_articles%>
</div>

app/views/categories/show.js.erb
  $('#filter').html("<%= j render "filter" %>")

app/views/layouts/_footer.html.erb
<div class="container">
<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://github.com/awadhwana"> Ankit Wadhwana</a>
    
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
</div>

app/views/layouts/_message.html.erb
<div class="row">
<div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, msg| %>
<div class='alert alert-<%="#{name}" %>'>
<a href="#" class="close" data-dismiss="alert">&#215;</a>
<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
</div>
<% end %>
</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Ankit\'s Blog',root_url, class: 'navbar-brand', id: 'logo' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_url%></li>
        <li><%= link_to 'Users', users_url%></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'View all categories', categories_url %></li>
              <li role="separator" class="divider"></li>
              <li><% Category.all.each do |c| %>
              <%= link_to c.name, category_path(c) %>
              <% end %></li>
              <% if (logged_in? && current_user.admin?) %>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Create category', new_category_url %></li>
              <%end%>
            </ul>
          </li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Create new article', new_article_url%></li>
              <li><%= link_to 'Create new user', signup_url %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'View all articles', articles_url%></li>
              <li><%= link_to 'View all users', users_url %></li>
              
            </ul>
          </li>
        <%end%>
      </ul>
      <%# <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> %>
      <ul class="nav navbar-nav navbar-right">
      <% if !logged_in? %>
        <li><%= link_to 'Login',login_url %></li>
        <li><%= link_to 'Sign up', 'signup'%></li>
        <% else%>
        <li><%= link_to 'Logout',logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.username.capitalize}"%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My articles',user_url(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Edit profile',edit_user_url(current_user) %></li>
              
        <%end%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Selfblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/message' %>
   <div class='container'>
    <%= yield %>
    </div >
    <div >
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>You're on the <b>ABOUT</b> page</h1>
<%= link_to 'Home', root_path%>

app/views/pages/home.html.erb
<div class='jumbotron'>
<h1>EAT SLEEP </h1>
<h1 style="text-align: center">CODE REPEAT!</h1>
<%=link_to 'Login', 'login', class: 'btn btn-primary'%>
<%=link_to 'Sign up', 'signup', class: 'btn btn-primary'%>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
 <div class="col-xs-8 col-xs-offset-2">
  <div class="panel panel-danger">
   <div class="panel-heading">
    <h2 class="panel-title">
    <%= pluralize(obj.errors.count, "error") %>
    prohibited this article from being saved:
    </h2>
   <div class="panel-body">
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
   </div>
  </div>
 </div>
 </div>
</div>
<% end %>   

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@user,:html =>{class: "form-horizontal",role:"form"}) do |f| %>
        <div class='form-group'>
        <div class="control-label col-sm-2">
         <%= f.label :username %> <br> 
         </div>
          <div class='col-sm-8'>
           <%= f.text_field :username, class: 'form-control', placeholder: 'Enter username',autofocus: true %>
         </div>
        </div>

        <div class='form-group'>
        <div class="control-label col-sm-2">
        <%= f.label :email %> <br>
        </div>
        <div class="col-sm-8">
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email",autofocus: true %>
        </div>
        </div>

        <div class='form-group'>
        <div class="control-label col-sm-2">
        <%= f.label :password %> <br>
        </div>
        <div class="col-sm-8">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password",autofocus: true %>
        </div>
        </div>


        <div class='form-group'>
        <div class="col-sm-offset-2 col-sm-10">
        <%=f.submit(@user.new_record? ? "signup" : "Update", class:'btn btn-primary btn-lg')%>
        </div>
        </div>
        <% end %>
        <%= link_to 'Back to Index', articles_url %>
 <div>
</div>

app/views/users/edit.html.erb
<h1 align='center'>EDIT USER</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All users</h1>

<div align="center">
<%= will_paginate %>
</div>
<% @users.each do |user|%>
    <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
    <div class="article-title">
    <%= link_to user.username, user_url(user) %>
    </div>

    <div style=" text-align:right; color: #737373" >
    <%= pluralize(user.articles.count, "article") %>   
    </div>
    <div class="article-body">
    <h4 >Email: <%= truncate(user.email) %></h4>
    </div>
    <% if logged_in? && (user == current_user || current_user.admin?) %>
        <div class="article-actions">
        <%= link_to "Edit this user", edit_user_url(user) %> |
        <%= link_to "Delete thise user",user_url(user), method: :delete,data: {confirm: "Are you sure?"} %>
        </div>
    <%end%>
    </div>
    </div>
    </div>
<%end%>
<div align="center">
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align='center'>NEW USER</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">WELCOME</h1>
<h4><%= @user.username.capitalize %>'s Articles</h4>
<div align="center">
<%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user.articles%>
<div align="center">
<%= will_paginate @user_articles %>
</div>